add dict type correction
XENONnT/straxen pull request #1028
Opened 2022-04-28 23:31 UTC by ahiguera-mx

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_
Add the option of a dict type correction
## What does the code in this PR do / what does it improve?
Add the option of a dict type correction
## Can you briefly describe how it works?

```
config =('se_gain_per_region', 'v1', True)
value = straxen.get_correction_from_cmt(run_id, config)
value[0]
```

## Can you give a minimal working example (or illustrate with a figure)?
'''
config =('se_gain_per_region', 'v1', True)
value = straxen.get_correction_from_cmt('021577', config)
value[0]
'''
_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

2022-05-10 14:38 UTC, WenzDaniel approved these changes
Looks good.

2022-05-10 23:46 UTC, ershockley approved these changes

2022-05-11 05:44 UTC, WenzDaniel requested changes
I think there is a bug. Put this on hold for now

2022-05-11 17:14 UTC, WenzDaniel approved these changes

2022-05-11 17:14 UTC, merged