Fix help of peak basics.
XENONnT/straxen pull request #1081
Opened 2022-09-22 08:15 UTC by WenzDaniel

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?
Small fix of peak basics help. 

Not sure if necessary as the byte order of the dtype does not change, but maybe it is saver to reprocess.

2022-09-22 11:22 UTC, dachengx commented
Looks good. We should be more careful on the definition.

2022-09-22 11:24 UTC, dachengx approved these changes

2022-09-22 11:31 UTC, JoranAngevaare requested changes
I think this is fine as long as we only merge it if we have a lineage change for some more fundamental reason (like https://github.com/XENONnT/straxen/pull/1079)

2022-10-12 07:19 UTC, JoranAngevaare approved these changes

2022-10-12 07:37 UTC, merged