Added peaks subtyping
XENONnT/straxen pull request #1152
Opened 2023-04-06 16:40 UTC by Jianyu010

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

enable processing for subtypings. See the note [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=jlong:peak_subtyping_study)

## Can you briefly describe how it works?

Added the corresponding plugin in `peaks` directory.

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

2023-04-13 16:15 UTC, dachengx requested changes

2023-04-13 16:26 UTC, Jianyu010 commented on straxen/plugins/peaks/peaks_subtyping.py
> +    checkout https://xe1t-wiki.lngs.infn.it/doku.php?id=jlong:sr0_few_electron_ps2_picking
Done

2023-04-13 16:26 UTC, Jianyu010 commented on straxen/plugins/peaks/peaks_subtyping.py
> +    FV_r = straxen.URLConfig(
Deleted

2023-04-13 16:27 UTC, Jianyu010 commented on straxen/plugins/peaks/peaks_subtyping.py
> +    max_area = straxen.URLConfig(
Deleted

2023-04-13 16:27 UTC, Jianyu010 commented on straxen/plugins/peaks/peaks_subtyping.py
> +        '''self.register_livetime()
Deleted

2023-04-22 18:58 UTC, dachengx commented on straxen/plugins/peaks/peaks_subtyping.py
> +                    whole_window_cond = (s2s_t > s1s_t[i]) & (s2s_t <= s1s_t[i] + full_dt)
Is there a potential bug? All other time window length is defined as `2 * full_dt`.

2023-04-26 17:37 UTC, dachengx requested changes

2023-04-26 17:41 UTC, Jianyu010 commented on straxen/plugins/peaks/peaks_subtyping.py
> +        while (dmask == PeakSubtyping.Undefined).sum() > 0:
这个的目的是穷尽所有6 。目前我自己跑没遇到过问题。。这个是根据peak数量来的，上限有点难啊，9e9?

2023-04-26 17:41 UTC, dachengx commented on straxen/plugins/peaks/peaks_subtyping.py
> +        while (dmask == PeakSubtyping.Undefined).sum() > 0:
OK. I will add that.

2023-04-26 17:44 UTC, Jianyu010 commented on straxen/plugins/peaks/peaks_subtyping.py
> +                        whole_window_cond = (pt > start_s2_t) & (pt <= max_time + 2 * drift_time_max)
They should not be the same. the 1full_dt was for S1, and 2full_dt was for S2

2023-04-26 20:19 UTC, dachengx approved these changes

2023-04-26 21:15 UTC, merged