Photon ionization correction on S2
XENONnT/straxen pull request #1247
Opened 2023-08-30 15:51 UTC by xzh19980906

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

## Can you briefly describe how it works?

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

2023-08-31 00:29 UTC, jingqiangye requested changes
Hi @xzh19980906 , thanks for the PR. The performance is good, see this [note](https://xe1t-wiki.lngs.infn.it/doku.php?id=jingqiang:straxen_review:1247).

However, I think we should not merge this PR until https://github.com/XENONnT/corrections/issues/221 is solved.

2023-08-31 18:05 UTC, jingqiangye approved these changes
Thanks @xzh19980906 for the update. The performance is satisfying, see [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=jingqiang:straxen_review:1247).

@dachengx any idea why the uni tests failed?

2023-09-01 00:44 UTC, dachengx commented
> @dachengx any idea why the uni tests failed?

Please just ignore it.

2023-09-01 11:16 UTC, shenyangshi commented
I think we are now overwriting cs2_area_fraction_top, cs2 and cs2_bottom, maybe we can create extra fields before this correction such as cs2_wo_aftcorr, cs2_area_fraction_top_wo_aftcorr,  cs2_bottom_wo_aftcorr so we can know what's the raw fields in the future.

2023-09-01 12:41 UTC, dachengx commented on straxen/plugins/events/corrected_areas.py
> +    __version__ = '0.3.1'
Please update this to a minor bump. I think PI is a pretty large change.

2023-09-01 13:59 UTC, xzh19980906 commented
> I think we are now overwriting cs2_area_fraction_top, cs2 and cs2_bottom, maybe we can create extra fields before this correction such as cs2_wo_aftcorr, cs2_area_fraction_top_wo_aftcorr, cs2_bottom_wo_aftcorr so we can know what's the raw fields in the future.

done. I think `'_wo_picorr'` is better

2023-09-01 14:07 UTC, shenyangshi approved these changes
Looks good to me. Sometime in the future we should totally rewrite this corrected_areas :)

2023-09-01 17:39 UTC, jingqiangye commented
Nice thanks guys!

2023-09-01 17:40 UTC, merged

2023-09-06 13:57 UTC, dachengx commented
In principle, we should also change the `PeakCorrectedAreas` plugin: https://github.com/XENONnT/straxen/blob/2e9eaaa7e146e8a19573849293aa796ac46630ee/straxen/plugins/peaks/peak_corrections.py#L10.