Som plugin
XENONnT/straxen pull request #1269
Opened 2023-09-24 23:35 UTC by LuisSanchez25

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

## Can you briefly describe how it works?

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

2023-09-29 07:46 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +    data_kind = {k: k for k in provides}
this makes no sense. Why are you creating new data kinds? arent you just adding columns to  peaklets?

2023-09-29 07:46 UTC, jmosbacher commented on straxen/plugins/merged_s2s/merged_s2s.py
> +    depends_on = ('peaklets', 'peaklet_classification_som', 'lone_hits')
I thought we said your plugin would be a drop-in replacement for the peaklet classification. So why are you adding it as an extra data_type?

2023-10-06 15:21 UTC, jmosbacher requested changes
You are committing to **collaborative** project. Please conform to existing coding styles so that others can easily read your work.

2023-10-06 15:21 UTC, jmosbacher commented on straxen/contexts.py
> +from straxen.plugins.peaklets.peaklet_classification_som import PeakletClassificationSOM
Please conform with the existing coding style for plugin management.
plugins are not imported explicitly.

2023-10-06 15:21 UTC, jmosbacher commented on straxen/contexts.py
> +    st.register(PeakletClassificationSOM)
```suggestion
    st.register(straxen.PeakletClassificationSOM)
```

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/__init__.py
> +#from . import peaklet_classification_som
Please remove comments so the plugin is available in the straxen namespace

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +import numpy.lib.recfunctions as rfn
please use 
```python
from numpy.lib import recfunctions as rfn
```

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +from straxen.plugins.peaklets.peaklet_classification import PeakletClassification
remove this import

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +class PeakletClassificationSOM(PeakletClassification):
```suggestion
class PeakletClassificationSOM(straxen.PeakletClassification):
```

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +        dtype = dict()
```suggestion
        dtype = {}
```

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +def recall_populations(dataset, weight_cube, SOM_cls_img, norm_factors):
please fix this

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +    [SOM_xdim, SOM_ydim, SOM_zdim] = weight_cube.shape
```suggestion
    xdim, ydim, zdim = weight_cube.shape
```

2023-10-06 15:21 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +    [SOM_xdim, SOM_ydim, SOM_zdim] = weight_cube.shape
please remove all these CamelCase variable names. Use snake_case for variable names.

2023-10-06 20:40 UTC, jmosbacher commented on straxen/plugins/peaklets/peaklet_classification_som.py
> +def SOM_cls_recall(array_to_fill, data_in_som_fmt, weight_cube, reference_map):
```suggestion
def som_cls_recall(array_to_fill, data_in_som_fmt, weight_cube, reference_map):
```

2023-10-06 20:41 UTC, LuisSanchez25 commented
The problem with changing the structure with how you suggested (just importing straxen and using straxen.PeakletClassification for the plugin) is that it creates a circular import error since straxen cant initialize it. This is also part of the reason I removed it from the __init__.py file since it can just be initialized later by the context, the other reason is that in [contexts](https://github.com/XENONnT/straxen/blob/master/straxen/contexts.py) if you look at line 88, it will register all plugins and since the SOM pluggin also provides peaklet classification I think it will cause problems. I could explicitly state not to fetch that config in the context where its registering everything but I think we probably do not want to hardcode that.

2023-10-06 20:42 UTC, jmosbacher approved these changes

2023-10-06 21:21 UTC, LuisSanchez25 commented
@jmosbacher all test have passed so I think this is ready to merge now

2023-10-07 04:25 UTC, jmosbacher approved these changes

2023-10-07 17:27 UTC, LuisSanchez25 commented
I cant merge the pull request so if you could merge it that would be great!

2023-10-09 19:32 UTC, merged