Add corrections_run_id for mini analysis
XENONnT/straxen pull request #1339
Opened 2024-02-28 23:53 UTC by mhliu0001

## What does the code in this PR do / what does it improve?
In the mini analysis code, `straxen` will look for the gain_model for the `run_id` specified. However, for MC runs the `run_id` is meaningless and should not be used to find corrections. Instead, a `corrections_run_id` should be provided for fuse/WFSim-based runs.

## Can you briefly describe how it works?
Add an extra key argument in the `mini_analysis` base class called "corrections_run_id". If this is provided, find the gain_model according to the `corrections_run_id`.

## Can you give a minimal working example (or illustrate with a figure)?

```python
import fuse
import cutax
import bokeh.plotting as bklt

st = fuse.context.full_chain_context(output_folder="./fuse_data",
                                     corrections_version='global_v14')

st.set_config({"path": "/project2/lgrandi/xenonnt/simulations/testing",
               "file_name": "pmt_neutrons_100.root",
               "entry_stop": 2,
               })

run_number = "mc_00"
st.make(run_number, "raw_records")
peaks = st.get_array(run_number,"peaks")
events = st.get_array(run_number,"event_basics")

fig = st.event_display_interactive(run_number, time_range=(events[0]['time'], events[0]['endtime']), corrections_run_id="026000")

bklt.output_file(filename="demo.html")
bklt.save(fig)
```

Before this PR straxen will try to load gain_model for run "mc_00", which will raise an error. Now it works.

2024-03-02 09:07 UTC, dachengx requested changes
straxen should not touch anything related to simulation. So I would recommend processing `corrections_run_id` in fuse. The `mini_analysis` can be also in fuse and it can call `mini_analysis` of straxen.

2024-03-02 09:07 UTC, dachengx commented on straxen/mini_analysis.py
> +                "corrections_run_id"
You can add another argument to `mini_analysis` function so that it can add additional `known_kwargs` to the default ones.

2024-03-02 09:07 UTC, dachengx commented on straxen/mini_analysis.py
> +                    if "corrections_run_id" in kwargs:
This part should be a stand-alone function called `process_to_pe` or other proper names. For straxen, this function can be as what it was. But for fuse, you can process `corrections_run_id` in it.

2024-10-16 23:12 UTC, yuema137 commented
As being discussed above, this will be implemented in `fuse` instead of `straxen`

2024-10-16 23:12 UTC, closed without merging