Plugins for position reconstruction with conditional normalizing flow
XENONnT/straxen pull request #1404
Opened 2024-08-02 01:04 UTC by juehang

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

## Can you briefly describe how it works?

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

2024-08-02 14:33 UTC, LuisSanchez25 commented
I wonder if it would make sense to integrate PeakPositionsFlow by inheriting from PeakPositionsBaseNT since it looks like there is a lot of overlap between what the two are computing and instead just having any additional datatypes you need get called in PeakPositionsFlow? Same with the events, in an ideal world we want to have as little duplicate code as possible but I am not 100% sure that this all can work like that.

Other than that, if the plugin is working and once it passes all the tests it will be fine by me

2024-08-02 14:50 UTC, juehang commented
> I wonder if it would make sense to integrate PeakPositionsFlow by inheriting from PeakPositionsBaseNT since it looks like there is a lot of overlap between what the two are computing and instead just having any additional datatypes you need get called in PeakPositionsFlow? Same with the events, in an ideal world we want to have as little duplicate code as possible but I am not 100% sure that this all can work like that.
> 
> Other than that, if the plugin is working and once it passes all the tests it will be fine by me

I found it quite difficult to inherit from `PeakPositionsBaseNT` because that one cannot currently deal with the extra fields for uncertainty, and if I inherited it in a naive way I would end up overloading almost everything.

2024-08-02 14:57 UTC, LuisSanchez25 commented
What do you mean by overloading everything?

2024-08-02 14:59 UTC, juehang commented
I just meant re-defining the methods to accommodate the new data fields

2024-08-12 21:45 UTC, yuema137 requested changes

2024-08-12 21:45 UTC, yuema137 commented on straxen/plugins/events/event_s2_positions_flow.py
> +    """Plugin to calculate position uncertainties for events.
Could you also add the relevant note in the docstring here? Same suggestion applied for other plugins too

2024-08-12 21:45 UTC, yuema137 commented on straxen/plugins/events/event_s2_positions_flow.py
> +    default_reconstruction_algorithm = straxen.URLConfig(
To me it looks that the `default_reconstruction_algorithm` is not used/called at all in this plugin. Is it a redundant config variable or something is missing in the compute function?

2024-08-12 21:51 UTC, yuema137 commented
Hi @juehang and @sebvetter thanks for this great work! The flow-based position reconstruction undoubtfully improves the interpretability of our ML efforts a lot! The PR is generally good and I put some minor suggestions in the review above. 

One thing that I'm a little bit concerned about is the speed. The flow-based model kindly gives us a position contour, unlike other algorithms which only offer deterministic outputs. This nice feature, on the other hand, usually also lead to much more computation cost. So it will be great if you could provide some kind of estimation on the speed (like compare the speed of mlp, cnn, gcn and flow model for the same dataset) so that we have a sense for it.

2024-08-13 11:46 UTC, sebvetter commented
Hi @yuema137 ,
In this note: https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:juehang:flow_posrec_proposal_sr2 you can find the attached plot
![cnf_vs_current_timing_per_sample](https://github.com/user-attachments/assets/5461d3ce-0917-4996-8f78-5f65b8294de7)

The Flow model is faster than the CNN

2024-08-15 15:56 UTC, dachengx commented on straxen/plugins/peaks/peak_positions.py
> +        "peak_positions_flow",
"peak_positions_flow" or "peak_positions_cnf"? :) I think the latter is better.

2024-08-26 02:16 UTC, dachengx approved these changes

2024-08-26 02:16 UTC, merged