Add fix integration window for the noise runs
XENONnT/straxen pull request #1457
Opened 2024-10-17 16:25 UTC by GiovanniVolta

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

The decreasing occupancy shown in [Peak finding a plugin for LED calibration processing](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:dsg:pmt:gains:dynamic_led_window#impact_on_gain_and_spe) is because the integration window of the noise run is moving too much inside the waveforms.

FIXME add plot hits before

## Can you briefly describe how it works?

Given that the pulser can/is causing some noise in the waveforms in coincidence with the LED (therefore it is fully caught by the LED on-runs integration window), it is better to place the integration window of the LED off-runs (aka noise runs) in proximity to where we would expect the LED.

The pulse is delayed by ~800 ns WRT the DAQ. Therefore the `expected_led_position` is placed at 86 ADC sample.
To discriminate between the noise and the led runs, we use a `minimum_hits_requirement` fixed at 500. note that the average number of hits in the gain (spe) runs is 700 (200) per PMT.

FIXME add screenshot

## Can you give a minimal working example (or illustrate with a figure)?

FIXME add plot hits after

FIXME add link to the note with update plots

_Please include the following if applicable:_
  - [x] _Update the docstring(s)_
  - [x] _Update the documentation_
  - [x] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

2024-10-17 16:27 UTC, FaroutYLq reviewed
Hi quick comment. Can you link a notes next to the default `expected_led_position` and `minimum_hits_requirement` in annotation?

2024-10-17 16:36 UTC, GiovanniVolta commented
This is the draft PR for fixing the issues causing the downward trend in occupancy. I need to make the plots and update the notes.

@tflehmke, please have a look and check it independently.

2024-10-21 17:29 UTC, GiovanniVolta commented
I have further checked the impact the fixed integration window for the noise on the occupancy and gain.
I have summarized [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:dsg:pmt:gains:dynamic_led_window#impact_on_gain_and_spe)
In a few words:

- the position of the window as a <2% impact on the estimation of the occupancy and gain
- the more stable condition (stability of occupancy and gain for different lengths of the integration window) is achieved by defining ``expected_led_position`` to 88 ADC

It is unclear why we have this behavior, and I would like @tflehmke , @sanaouahada, and @MaxiA04  to keep looking into it. Given the impact is within the 2.5% value that we use to model the time trend of the gain, I would suggest moving on.

2024-10-22 09:59 UTC, tflehmke commented on straxen/plugins/led_cal/led_calibration.py
> +        default=500,
For the bottom array I get around 300-500 hits per PMT and chunk. The noise run has O(1) hits. I think we should decrease the value to around 100.

2024-10-22 10:10 UTC, tflehmke submitted a review, later dismissed

2024-10-22 13:48 UTC, dachengx requested changes
We should replace the `minimum_hits_requirement` by the tagging, like https://github.com/XENONnT/cutax/blob/87f4d25a2bd36cbb96fefab26c00bc3779b47396/cutax/utils.py#L190. The tag can tell us which run is a noise run.

2024-10-23 13:39 UTC, dachengx commented on straxen/plugins/led_cal/led_calibration.py
> +        if no hits are identified :minimum_hits_requirement: Minimum hits requirement for the
`minimum_hits_requirement` is not needed anymore

2024-10-24 11:24 UTC, dachengx approved these changes

2024-10-24 11:24 UTC, dachengx commented on straxen/plugins/led_cal/led_calibration.py
> +    noise_run_comments = straxen.URLConfig(
This line is a very good implementation! @GiovanniVolta

2024-10-24 11:24 UTC, merged