Update led_calibration.py
XENONnT/straxen pull request #1462
Opened 2024-10-28 12:02 UTC by GiovanniVolta

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

I realized that there are run_ids with more than one comment, which will cause an error as it is right now. The first comment is always from the automatic script.

I have fixed that and I have added a check for verifying that the first comments has the right format.

## Can you briefly describe how it works?

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

2024-10-28 12:17 UTC, dachengx submitted a review, later dismissed

2024-10-28 14:42 UTC, GiovanniVolta commented
[Here](https://xenonnt.slack.com/archives/C016UJZ090B/p1730120125020709), @dachengx suggested changing the config in the test instead of adding a specific run_id for the led_calibration. Unfortunately, I don't know where to change it. If you prefer me to change the config, I need some help

2024-10-28 15:04 UTC, GiovanniVolta commented
Ah, of course, the data are not stored so the test are still failing

2024-10-28 15:48 UTC, dachengx requested changes

2024-10-28 15:48 UTC, dachengx commented on straxen/plugins/led_cal/led_calibration.py
> +    defualt_run_comments = straxen.URLConfig(
Please assign its type to be `list`.

2024-10-28 16:00 UTC, GiovanniVolta commented on straxen/plugins/led_cal/led_calibration.py
> +    defualt_run_comments = straxen.URLConfig(
Done

2024-10-29 13:08 UTC, GiovanniVolta commented
@dachengx @minzhong98 @MerzJohannes @yuema137 shall we proceed here?

2024-10-29 13:09 UTC, dachengx approved these changes

2024-10-29 13:09 UTC, merged

2024-10-29 13:09 UTC, GiovanniVolta commented
Thank you Dacheng <3