Update gain_models.py
XENONnT/straxen pull request #208
Opened 2020-09-06 16:15 UTC by GiovanniVolta

Gas xenon gain during cooling phase: 2020-08-26. PTMs at 1.5 kV a part PMT 116 and 195 which were at 1,3 kV. PMTs 354, 362, 386, 427 were off.

Note that during led calibration of August 26th PMTs 264, 272, 285, 300, 308, 311, 313, 316, 325, 339, 356, 359 didn't acquire data. For them I have used the results from 2020-08-23. 
For PMT 137, which were always off, I have used the result from 2020-07-24.

2020-09-07 06:56 UTC, WenzDaniel commented
Hi Giovanni, thanks. @feigaodm @skazama  this change is ready for merge.

2020-09-07 06:56 UTC, WenzDaniel approved these changes

2020-09-07 06:59 UTC, skazama commented
@GiovanniVolta @WenzDaniel Thanks. Do we also need to change [here](https://github.com/XENONnT/straxen/blob/master/straxen/contexts.py#L25) until a nice CMT tool becomes ready to handle?

2020-09-07 07:00 UTC, WenzDaniel commented
If these cane shall be taken as the new defaults yes.

2020-09-08 06:46 UTC, skazama commented
I think the model which @GiovanniVolta implemented can be used as a default until we have CMT tool to handle the time-dependent model. @GiovanniVolta Can you please also modify [https://github.com/XENONnT/straxen/blob/master/straxen/contexts.py#L25](here)?

2020-09-08 06:58 UTC, jorana requested changes
Perhaps it's good to mention that if we indeed use this model we have to reprocess the following plugins (given that we implement @skazama comment):
![afbeelding](https://user-images.githubusercontent.com/22295914/92443069-3b065e80-f1b1-11ea-850a-7cd41f5a0d01.png)

Furthermore, we could use this repo https://github.com/XENONnT/strax_auxiliary_files/ to start saving these gains.

2020-09-08 13:57 UTC, GiovanniVolta commented
> 
> 
> I think the model which @GiovanniVolta implemented can be used as a default until we have CMT tool to handle the time-dependent model. @GiovanniVolta Can you please also modify [https://github.com/XENONnT/straxen/blob/master/straxen/contexts.py#L25](here)?

Sorry Shingo, I have been busy today. I will do it

2020-09-11 07:57 UTC, GiovanniVolta commented
I have added in the context the new gain model:  'TemporaryGXe_1500V_PMT116_1300_PMT195_1300'

2020-09-11 08:01 UTC, jorana requested changes

2020-09-11 08:01 UTC, jorana commented on straxen/contexts.py
> +    gain_model=('to_pe_constant', '1300V_20200428', 'TemporaryGXe_1500V_PMT116_1300_PMT195_1300'),
Hi Giovanni, thanks! Can you change it to:
```
gain_model=('to_pe_constant','TemporaryGXe_1500V_PMT116_1300_PMT195_1300'),
```

2020-09-11 09:23 UTC, jorana approved these changes

2020-09-11 09:24 UTC, merged