Add check for daq-reader processing threads
XENONnT/straxen pull request #347
Opened 2021-01-26 16:56 UTC by jorana

**What is the problem / what does the code in this PR do**
Check that redax / dispatcher is not writing wrong threads to wrong runs.

**Can you briefly describe how it works?**
Each of the readers is registered, let's check that we don't get reader_6 for non NV data, etc.

2021-01-26 18:07 UTC, WenzDaniel approved these changes
Thank you for the quick fix. Lets hope we wont need it in the future.

2021-01-27 08:12 UTC, darrylmasson reviewed
"Sloppy" is a word to describe this. We're passing through separately the keys and values of `daq_config.processing_threads`, and not using them in a combined and coherent way.

2021-01-27 08:28 UTC, jorana commented
> 
> 
> "Sloppy" is a word to describe this. We're passing through separately the keys and values of `daq_config.processing_threads`, and not using them in a combined and coherent way.

@darrylmasson I wasn't anticipating that we'd keep this implemented for long, you want me to change it?

2021-01-27 08:35 UTC, darrylmasson commented
We have two options: a quick and dirty implementation, or something that makes fuller use of the information we can access. Do we want DAQReader to always just take whatever files are present, or do we think it's reasonable to actually check that it's seeing the files it should? We had a similar problem much earlier when redax wasn't correctly allocating processing threads, and this is quite similar.

2021-01-27 08:50 UTC, jorana commented
> 
> 
> We have two options: a quick and dirty implementation, or something that makes fuller use of the information we can access. Do we want DAQReader to always just take whatever files are present, or do we think it's reasonable to actually check that it's seeing the files it should? We had a similar problem much earlier when redax wasn't correctly allocating processing threads

Okay, based on your phrasing, I think you imply the latter. Thanks for the feedback. To implement the latter:
- Indeed just use the dict instead of keys and values separately;
- use a counter to see that the number in each chunk is `le` the #processing threads from the rundoc (last few chunks don't need to have all threads per se).

2021-01-27 12:56 UTC, darrylmasson requested changes
Some typos

2021-01-27 12:56 UTC, darrylmasson commented on straxen/plugins/daqreader.py
> +        return '_'.join(partial_chunk.split('_')[-1])
`reader0_reader_0_threadid` -> `t_h_r_e_a_d_i_d`, is that what we are interested in, or should it be `[:-1]`?

2021-01-27 13:11 UTC, jorana commented on straxen/plugins/daqreader.py
> +        self.n_readout_treads = sum(self.config['readout_threads'].values())
Thanks Darryl, well spotted, should be fixed now.

2021-01-27 13:14 UTC, jorana commented
Thanks @darrylmasson, well spotted mistakes. Just tried it on two runs in non production mode. One processed all right the other gave:
`/live_data/xenonnt/012118/THE_END. Got reader6_reader_0`

Are you happy with this behavior with the counting of threads or would you argue for smarter checks?

2021-01-27 13:34 UTC, darrylmasson approved these changes

2021-01-27 21:42 UTC, merged