Version bump of hitlets
XENONnT/straxen pull request #690
Opened 2021-10-11 11:30 UTC by WenzDaniel

_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?
Version bump because of https://github.com/AxFoundation/strax/pull/549.

2021-10-11 11:35 UTC, WenzDaniel commented
@ershockley I did a bug fix in hitlet processing. This will require reprocessing of `hitlets_nv` and `hitlets_mv`. I have a question regarding managing reprocessing. Currently, the muon-veto plugins are set-up such that they are inherited from the neutron-veto plugins. Hence, their lineage also has the version of the corresponding neutron-veto plugin encoded. This means whenever I change the version of the neutron-veto plugin this will also change the lineage/hash of the muon-veto plugin, indicating that reprocessing is needed. 
However, from a human perspective would you prefer that I bump the version of the muon-veto plugins, too? Would this help you to keep track for reprocessing?

2021-10-11 12:03 UTC, JoranAngevaare requested changes
Perhaps we should put strax v1.0.1 in the requirements file? It won't work now but this PR can be merged after releasing the new strax version

2021-10-11 16:13 UTC, ershockley commented
@WenzDaniel I don't think it is needed to manually up the versions. We store the hashes for each context/straxen version that goes into base environment and don't really track what individual plugin versions are. So I think it is fine like this.

2021-10-15 16:51 UTC, ershockley approved these changes

2021-10-18 14:42 UTC, merged