Add n_tpc_top_pmts parameter to build separate array summed waveform
XENONnT/straxen pull request #721
Opened 2021-10-30 09:42 UTC by DCichon

Adds a parameter to peaklet processing in order to be able to build the summed waveform over a single array only (see https://github.com/AxFoundation/strax/pull/565 for more details).

2022-10-12 08:14 UTC, jmosbacher requested changes
One very important thing I dont see here is bumping the plugin version. Since the plugin will produce different data, its crucial that the version is changes so that the lineage changes and data is reprocessed with the new plugin even if it was processed previously with the old one.

2022-10-12 08:18 UTC, jmosbacher commented
Updated to use URLConfigs.

2022-10-14 05:06 UTC, FaroutYLq approved these changes
Tested and it is working after e20104f673dcfe8d7448ec2513c554ef4c723ce6

2022-10-14 07:01 UTC, jmosbacher commented on straxen/plugins/peaklet_processing.py
> +                n_top_channels=n_top_pmts)
Yesh, looks like a typo :)

2022-10-14 07:04 UTC, JoranAngevaare commented
I'll remake this PR in a sec

2022-10-14 07:04 UTC, closed without merging

2022-10-17 12:20 UTC, JoranAngevaare commented
I also tested that the data produced yields the same for:
1. current master
2. the version that Lanqing tested (https://github.com/XENONnT/straxen/pull/721)
3. the updates that I made to that later (https://github.com/XENONnT/straxen/pull/1099)

The notebook for the test is here:
https://github.com/XENONnT/analysiscode/pull/98