Performance update for binomial test
XENONnT/straxen pull request #783
Opened 2021-11-30 17:15 UTC by zhut19

## What does the code in this PR do / what does it improve?
Speeds up the non-discrete binomial test p-value computation for S1 area fraction top

## Can you briefly describe how it works?
Use secant method instead of grid search for finding the mode and j-value from binomial pmf

2021-12-01 10:31 UTC, JoranAngevaare commented
Thanks @zhut19! Do you have a feeling for the performance upgrade? Do we meed to increment the plugin version?

I think @GiovanniVolta can best comment on testing that the results are the same.

2021-12-01 11:03 UTC, GiovanniVolta commented
Hello everyone, me and Tyaniu already discuss it. This improvement looks very promising. However, I would like to test it and compare the two method. I will do it as soon as possible.

2021-12-02 07:25 UTC, WenzDaniel commented
As mentioned by Joran some benchmark would be interesting. Can be posted in the Team B channel in slack.

2021-12-09 09:03 UTC, WenzDaniel commented on straxen/plugins/event_patternfit.py
> +@numba.njit
Is not it possible to use numbas vectorize routine? See removed line 344.

2021-12-09 11:38 UTC, WenzDaniel reviewed
From a technical point of view it looks fine to me. Although I have not checked if the change makes any logical sense.

2021-12-09 11:46 UTC, GiovanniVolta commented
Hey @WenzDaniel, besides the issue I pointed out in my review, I think @zhut19 proposal is better than what we are doing right now

2021-12-09 12:03 UTC, WenzDaniel commented
So we can go ahead and merge?

2021-12-09 12:52 UTC, GiovanniVolta commented
>So we can go ahead and merge?

No, my review has not been addressed yet

2021-12-09 13:26 UTC, WenzDaniel commented
Convert it to a draft until Giovannis comments are addressed.

2021-12-09 13:29 UTC, GiovanniVolta requested changes

2021-12-09 13:30 UTC, GiovanniVolta commented
Sorry guys, I am terrible with GitHub. I didn't submit my review

2021-12-11 10:25 UTC, GiovanniVolta approved these changes
Even if there is room for improvement, I am happy with this. I am making a summary note that describe how we are computing the p-value. I hope it will be useful for the later.
Could you please Tianyu update the version number?

2021-12-13 09:50 UTC, WenzDaniel commented
@zhut19  as soon as you bump the version I will make the new release.

2021-12-13 14:14 UTC, merged