Extend save when
XENONnT/straxen pull request #879
Opened 2022-01-13 09:14 UTC by WenzDaniel

## What does the code in this PR do / what does it improve?
Uses https://github.com/AxFoundation/strax/pull/631 to store pulse count information without storing records. Changes lineage of low level plugin so only merge when larger reprocessing campaign is planned. Also requires to bump strax requirement. 

- [ ] Bump strax requirement once https://github.com/AxFoundation/strax/pull/631 is merged.

2022-01-13 16:37 UTC, JoranAngevaare requested changes
@WenzDaniel , there is no reason to bump the version of these low level data types right?

Additionally, should the `save_when` be immutable just to be sure?

2022-01-13 16:37 UTC, JoranAngevaare commented on straxen/plugins/nveto_recorder.py
> +                 'lone_raw_records_nv': strax.SaveWhen.EXPLICIT,
I would consider also setting this to TARGET? It's not that easy to compute

2022-01-13 16:37 UTC, JoranAngevaare commented on straxen/plugins/pulse_processing.py
> +                 'veto_regions': strax.SaveWhen.EXPLICIT,
```suggestion
                 'veto_regions': strax.SaveWhen.TARGET,
```

2022-01-14 07:30 UTC, WenzDaniel commented
Okay I addressed all your comments and changed the code accordingly. I did not have any strong opinions. Regarding the version you are absolutely right :D  Usually I forget it when I have to and now I was too eager :D

2022-01-21 10:08 UTC, JoranAngevaare approved these changes
Very nice! Thanks

2022-02-02 13:22 UTC, JoranAngevaare commented
@WenzDaniel , do you want to have a look at the tests?

2022-02-12 08:41 UTC, JoranAngevaare commented
some tweaks are needed, we should not forget to bump the version https://github.com/AxFoundation/strax/pull/648

2022-02-14 08:07 UTC, JoranAngevaare commented
@WenzDaniel https://github.com/XENONnT/straxen/pull/879/commits/8c62125688590594f4f0938f922e3b4e7eee3c2e finished successfully :)

2022-02-16 06:57 UTC, merged